version: "3.9"

services:
  app-db:
    image: postgres
    container_name: app-data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin-test
      - POSTGRES_PASSWORD=ioasys
      - POSTGRES_DB=app-db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - app-db
    depends_on:
      - app-db
volumes:
  pgdata:
    driver: local
